### ISSUE TITLE
Make an About.xml

### ISSUE THREAD

**Issue by Chunnyluny** [Chunnyluny-RimWorld-Modding/DogApparel#3]
If everything is described in the About.xml then it can be moved to done, if not, than we need to add some more information.

**Comment by Chunnyluny** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Progress, current tasks](https://trello.com/c/xR0gHp1J/4-progress-current-tasks)

**Comment by Chunnyluny** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issues from GitHub project.](https://trello.com/c/Pyk4CXRz/6-issues-from-github-project)

**Comment by HapiBodhi** [comment]
I'm not that well versed in GitHub, but if this issue is solved shouldn't you close it?

**Comment by Chunnyluny** [comment]
it is not yet done, because I still need to edit the description, it has now placeholder text.
