### ISSUE TITLE
Increase Team

### ISSUE THREAD

**Issue by isyuricunha** [Chunnyluny-RimWorld-Modding/DogApparel#8]
Hi @Chunnyluny, 
How are you?

You need help with this mod?

Cheers,
Yuri.

**Comment by Chunnyluny** [comment]
> Hi @Chunnyluny, 
> How are you?
> 
> You need help with this mod?
> 
> Cheers,
> Yuri.

If it is possible yes. It is my first mod . It uses some xml and some c

**Comment by Chunnyluny** [comment]
> Hi @Chunnyluny, 
> How are you?
> 
> You need help with this mod?
> 
> Cheers,
> Yuri.

I'm fine I need some help since this is my first mod. For example the structure is where I get stuck. If it is possible yes. It is my first mod . It uses some xml and some c#

**Comment by isyuricunha** [comment]
Sure, I understand. If you'd like, I can help you. Lately, I've been working with some mods for RimWorld/Necesse/Guild 3.

I'm a Database Administrator, and besides SQL, XML is one of my primary languages... Although XML is not a programming language.

Do you have an email, Discord, Telegram, or something similar?

**Comment by Chunnyluny** [comment]
> Sure, I understand. If you'd like, I can help you. Lately, I've been working with some mods for RimWorld/Necesse/Guild 3.
> 
> I'm a Database Administrator, and besides SQL, XML is one of my primary languages... Although XML is not a programming language.
> 
> Do you have an email, Discord, Telegram, or something similar?

Yes I have a discord server which you can join through this link. I have made a channel where the mod project is specially discussed. The link https://discord.gg/uu7pxAHQ to join.
